### ISSUE TITLE
nginx - can't upload files to vhost because of size limit

### ISSUE THREAD

**Issue by ciotlosm** [bestlibre/hassio-addons#35]
Trying to upload files to a vhost behind nginx results in failure

![screen shot 2017-12-03 at 21 50 17](https://user-images.githubusercontent.com/7738048/33529075-13e8740e-d874-11e7-8547-98e89752e5f7.png)

**Comment by penright** [comment]
@ciotlosm did you close this because it was fixed?

I am getting this ....
2018/01/18 07:02:22 [error] 27#27: *34229 client intended to send too large body: 7176858 bytes, client: 69.x.x.x, server: nas.xxxxxxx.net, request: "POST /3.0/index.php?explorer/fileUpload&path=%2FUser%2Fpenright%2Fhome%2FMovies%2FHomeMovies%2F HTTP/2.0", host: "nas.xxxxx.net", referrer: "https://nas.xxxxxx.net/3.0/index.php?/explorer&type=iframe&path="

**Comment by ciotlosm** [comment]
@penright Just noticed this. I closed my post because I assumed my approach was not ok for my intended use. 

Indeed it is still not working.

**Comment by ciotlosm** [comment]
I'll reopen this and when I get time see how to allow this from options. If you have any ideas, a Pull Request is welcome

**Comment by penright** [comment]
I would love to help, just have not played with docker. HASS.IO hides so much.  30,000 looks like config.json and run.sh needs to be updated. Let me fork it and I will look.

**Comment by ciotlosm** [comment]
Should be fairly straight forward. If you know exactly the nginx settings that needs to get updated and the section I can help with that somewhere early next week.

**Comment by penright** [comment]
I think [http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)

I have looked at it some ... Now it looks like config.json/vhost.mustache.  I need to study the syntax of mustache. For me this is a great learning, but can I hack the production Nginx conf just to test if I am right? I assume the HASS.IO writes the .conf file when clicked on save.

**Comment by penright** [comment]
Can you access another docker ie Nginx (vhost) from the addon terminal?
I will configure the "developers" ssh this weekend, just curious about the other?

**Comment by ciotlosm** [comment]
@penright I don't think so. You need access to host OS and use docker commands to attach to a running container. Best would be to build locally one nginx container to try stuff. 

See: https://home-assistant.io/developers/hassio/addon_testing/

**Comment by bestlibre** [comment]
I have add the option. Can you test it ? The option is named "max_body_size" and should be set per vhost. If it works, I will add the doc.

**Comment by penright** [comment]
> @bestlibre Can you test it

I made my first pass. 0.1.9 upgraded to 0.1.10 without issue.

According to the Nginx website, 0 disables checking
[http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)
**_Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. If the size in a request exceeds the configured value, the 413 (Request Entity Too Large) error is returned to the client. Please be aware that browsers cannot correctly display this error. Setting size to 0 disables checking of client request body size._**


Added the option
```
    {
      "vhost": "nas.xxxxx.net",
      "remote": "192.168.1.18",
      "port": "8181",
      "certname": "nas",
      "default_server": false,
      "max_body_size": "0"
    },
```
My first attempt is failing. It could be the server. It's been awhile but I remember some 400ish error and I am not see it. Also it was failing at 7176858 bytes and now it is 8389803 bytes. May need to try a different number and see if the error follows the setting. Curious what @ciotlosm sees  ..

```
2018/02/06 09:12:41 [error] 28#28: *125 client intended to send too large body: 8389803 bytes, client: 69.148.62.34, server: nas.xxxxxx.net, request: "POST /3.0/index.php?explorer/fileUpload&path=%2FUser%2Fpenright%2Fhome%2FPP%2FGirlsSinging%2FOrig%2F HTTP/2.0", host: "nas.xxxxxx.net", referrer: "https://nas.xxxxxx.net/3.0/index.php?/explorer&type=iframe&path="
```

**Comment by penright** [comment]
Bottom line, it fixed the issue.
I tried a setting of 500m. Made the change, restarted and it worked. Then I started thinking, I don't remember restarting after making the first change "max_body_size" of 0. So I went back and tested 0 and it worked. I think my first test was flawed. Sorry for the confusion.

Maybe another topic, now when I look at the log I am seeing these ....
```
2018/02/06 09:38:33 [warn] 27#27: *24 a client request body is buffered to a temporary file /var/tmp/nginx/client_body/0000000112, client: 69.148.62.34, server: nas.xxxxx.net, request: "POST /3.0/index.php?explorer/fileUpload&path=%2FUser%2Fpenright%2Fhome%2FPP%2FGirlsSinging%2FOrig%2F HTTP/2.0", host: "nas.xxxxxxxx.net", referrer: "https://nas.xxxxx.net/3.0/index.php?/explorer&type=iframe&path="
```
Any thoughts? Normal?

**Comment by ciotlosm** [comment]
@penright normal as you might not have enough memory to hold the request so it got swapped to disk.

**Comment by ciotlosm** [comment]
I'll close the issue as it is fixed, thanks for help with the test.
